### ISSUE TITLE
Support for AER issues

### ISSUE THREAD

**Issue by bluecmd** [facebookincubator/pcicrawler#2]
Hi,

Thanks for releasing this tool! Looks neat.

Have you considered adding support for reading AER state? AER can be very messy to manually parse so having something like pcicrawler being able to make sense of it, especially at scale, would be neat.

Reference documentation: 
https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-bus-pci-devices-aer_stats

**Comment by gabhijit** [comment]
This issue was accidentally referenced. The actual issue is #3.

**Comment by ashwinp-fb** [comment]
Thanks bluecmd! Reading AER state looks like a good enhancement to the pcicrawler tool and I'd be open to adding that capability when I find some time. Please feel free to contribute too!

**Comment by mmlcbr** [comment]
087a3f857191a108770b034f0904a77da868d307
